// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	approvalrequest "github.com/openchoreo/openchoreo/internal/openchoreo-api/services/approvalrequest"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CancelApprovalRequest provides a mock function with given fields: ctx, namespaceName, approvalRequestName
func (_m *MockService) CancelApprovalRequest(ctx context.Context, namespaceName string, approvalRequestName string) (*v1alpha1.ApprovalRequest, error) {
	ret := _m.Called(ctx, namespaceName, approvalRequestName)

	if len(ret) == 0 {
		panic("no return value specified for CancelApprovalRequest")
	}

	var r0 *v1alpha1.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ApprovalRequest, error)); ok {
		return rf(ctx, namespaceName, approvalRequestName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ApprovalRequest); ok {
		r0 = rf(ctx, namespaceName, approvalRequestName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, approvalRequestName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CancelApprovalRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelApprovalRequest'
type MockService_CancelApprovalRequest_Call struct {
	*mock.Call
}

// CancelApprovalRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - approvalRequestName string
func (_e *MockService_Expecter) CancelApprovalRequest(ctx interface{}, namespaceName interface{}, approvalRequestName interface{}) *MockService_CancelApprovalRequest_Call {
	return &MockService_CancelApprovalRequest_Call{Call: _e.mock.On("CancelApprovalRequest", ctx, namespaceName, approvalRequestName)}
}

func (_c *MockService_CancelApprovalRequest_Call) Run(run func(ctx context.Context, namespaceName string, approvalRequestName string)) *MockService_CancelApprovalRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_CancelApprovalRequest_Call) Return(_a0 *v1alpha1.ApprovalRequest, _a1 error) *MockService_CancelApprovalRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CancelApprovalRequest_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ApprovalRequest, error)) *MockService_CancelApprovalRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DecideApprovalRequest provides a mock function with given fields: ctx, namespaceName, approvalRequestName, result, comment
func (_m *MockService) DecideApprovalRequest(ctx context.Context, namespaceName string, approvalRequestName string, result v1alpha1.ApprovalResult, comment string) (*v1alpha1.ApprovalRequest, error) {
	ret := _m.Called(ctx, namespaceName, approvalRequestName, result, comment)

	if len(ret) == 0 {
		panic("no return value specified for DecideApprovalRequest")
	}

	var r0 *v1alpha1.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, v1alpha1.ApprovalResult, string) (*v1alpha1.ApprovalRequest, error)); ok {
		return rf(ctx, namespaceName, approvalRequestName, result, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, v1alpha1.ApprovalResult, string) *v1alpha1.ApprovalRequest); ok {
		r0 = rf(ctx, namespaceName, approvalRequestName, result, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, v1alpha1.ApprovalResult, string) error); ok {
		r1 = rf(ctx, namespaceName, approvalRequestName, result, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_DecideApprovalRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecideApprovalRequest'
type MockService_DecideApprovalRequest_Call struct {
	*mock.Call
}

// DecideApprovalRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - approvalRequestName string
//   - result v1alpha1.ApprovalResult
//   - comment string
func (_e *MockService_Expecter) DecideApprovalRequest(ctx interface{}, namespaceName interface{}, approvalRequestName interface{}, result interface{}, comment interface{}) *MockService_DecideApprovalRequest_Call {
	return &MockService_DecideApprovalRequest_Call{Call: _e.mock.On("DecideApprovalRequest", ctx, namespaceName, approvalRequestName, result, comment)}
}

func (_c *MockService_DecideApprovalRequest_Call) Run(run func(ctx context.Context, namespaceName string, approvalRequestName string, result v1alpha1.ApprovalResult, comment string)) *MockService_DecideApprovalRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(v1alpha1.ApprovalResult), args[4].(string))
	})
	return _c
}

func (_c *MockService_DecideApprovalRequest_Call) Return(_a0 *v1alpha1.ApprovalRequest, _a1 error) *MockService_DecideApprovalRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_DecideApprovalRequest_Call) RunAndReturn(run func(context.Context, string, string, v1alpha1.ApprovalResult, string) (*v1alpha1.ApprovalRequest, error)) *MockService_DecideApprovalRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetApprovalRequest provides a mock function with given fields: ctx, namespaceName, approvalRequestName
func (_m *MockService) GetApprovalRequest(ctx context.Context, namespaceName string, approvalRequestName string) (*v1alpha1.ApprovalRequest, error) {
	ret := _m.Called(ctx, namespaceName, approvalRequestName)

	if len(ret) == 0 {
		panic("no return value specified for GetApprovalRequest")
	}

	var r0 *v1alpha1.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ApprovalRequest, error)); ok {
		return rf(ctx, namespaceName, approvalRequestName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ApprovalRequest); ok {
		r0 = rf(ctx, namespaceName, approvalRequestName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, approvalRequestName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetApprovalRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApprovalRequest'
type MockService_GetApprovalRequest_Call struct {
	*mock.Call
}

// GetApprovalRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - approvalRequestName string
func (_e *MockService_Expecter) GetApprovalRequest(ctx interface{}, namespaceName interface{}, approvalRequestName interface{}) *MockService_GetApprovalRequest_Call {
	return &MockService_GetApprovalRequest_Call{Call: _e.mock.On("GetApprovalRequest", ctx, namespaceName, approvalRequestName)}
}

func (_c *MockService_GetApprovalRequest_Call) Run(run func(ctx context.Context, namespaceName string, approvalRequestName string)) *MockService_GetApprovalRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetApprovalRequest_Call) Return(_a0 *v1alpha1.ApprovalRequest, _a1 error) *MockService_GetApprovalRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetApprovalRequest_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ApprovalRequest, error)) *MockService_GetApprovalRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ListApprovalRequests provides a mock function with given fields: ctx, namespaceName, filter, opts
func (_m *MockService) ListApprovalRequests(ctx context.Context, namespaceName string, filter approvalrequest.ListFilter, opts services.ListOptions) (*services.ListResult[v1alpha1.ApprovalRequest], error) {
	ret := _m.Called(ctx, namespaceName, filter, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListApprovalRequests")
	}

	var r0 *services.ListResult[v1alpha1.ApprovalRequest]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, approvalrequest.ListFilter, services.ListOptions) (*services.ListResult[v1alpha1.ApprovalRequest], error)); ok {
		return rf(ctx, namespaceName, filter, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, approvalrequest.ListFilter, services.ListOptions) *services.ListResult[v1alpha1.ApprovalRequest]); ok {
		r0 = rf(ctx, namespaceName, filter, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ApprovalRequest])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, approvalrequest.ListFilter, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, filter, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListApprovalRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApprovalRequests'
type MockService_ListApprovalRequests_Call struct {
	*mock.Call
}

// ListApprovalRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - filter approvalrequest.ListFilter
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListApprovalRequests(ctx interface{}, namespaceName interface{}, filter interface{}, opts interface{}) *MockService_ListApprovalRequests_Call {
	return &MockService_ListApprovalRequests_Call{Call: _e.mock.On("ListApprovalRequests", ctx, namespaceName, filter, opts)}
}

func (_c *MockService_ListApprovalRequests_Call) Run(run func(ctx context.Context, namespaceName string, filter approvalrequest.ListFilter, opts services.ListOptions)) *MockService_ListApprovalRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(approvalrequest.ListFilter), args[3].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListApprovalRequests_Call) Return(_a0 *services.ListResult[v1alpha1.ApprovalRequest], _a1 error) *MockService_ListApprovalRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListApprovalRequests_Call) RunAndReturn(run func(context.Context, string, approvalrequest.ListFilter, services.ListOptions) (*services.ListResult[v1alpha1.ApprovalRequest], error)) *MockService_ListApprovalRequests_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
