// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateApprovalPolicy provides a mock function with given fields: ctx, namespaceName, ap
func (_m *MockService) CreateApprovalPolicy(ctx context.Context, namespaceName string, ap *v1alpha1.ApprovalPolicy) (*v1alpha1.ApprovalPolicy, error) {
	ret := _m.Called(ctx, namespaceName, ap)

	if len(ret) == 0 {
		panic("no return value specified for CreateApprovalPolicy")
	}

	var r0 *v1alpha1.ApprovalPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ApprovalPolicy) (*v1alpha1.ApprovalPolicy, error)); ok {
		return rf(ctx, namespaceName, ap)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ApprovalPolicy) *v1alpha1.ApprovalPolicy); ok {
		r0 = rf(ctx, namespaceName, ap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ApprovalPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ApprovalPolicy) error); ok {
		r1 = rf(ctx, namespaceName, ap)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateApprovalPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApprovalPolicy'
type MockService_CreateApprovalPolicy_Call struct {
	*mock.Call
}

// CreateApprovalPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - ap *v1alpha1.ApprovalPolicy
func (_e *MockService_Expecter) CreateApprovalPolicy(ctx interface{}, namespaceName interface{}, ap interface{}) *MockService_CreateApprovalPolicy_Call {
	return &MockService_CreateApprovalPolicy_Call{Call: _e.mock.On("CreateApprovalPolicy", ctx, namespaceName, ap)}
}

func (_c *MockService_CreateApprovalPolicy_Call) Run(run func(ctx context.Context, namespaceName string, ap *v1alpha1.ApprovalPolicy)) *MockService_CreateApprovalPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ApprovalPolicy))
	})
	return _c
}

func (_c *MockService_CreateApprovalPolicy_Call) Return(_a0 *v1alpha1.ApprovalPolicy, _a1 error) *MockService_CreateApprovalPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateApprovalPolicy_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ApprovalPolicy) (*v1alpha1.ApprovalPolicy, error)) *MockService_CreateApprovalPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApprovalPolicy provides a mock function with given fields: ctx, namespaceName, approvalPolicyName
func (_m *MockService) DeleteApprovalPolicy(ctx context.Context, namespaceName string, approvalPolicyName string) error {
	ret := _m.Called(ctx, namespaceName, approvalPolicyName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApprovalPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, approvalPolicyName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteApprovalPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApprovalPolicy'
type MockService_DeleteApprovalPolicy_Call struct {
	*mock.Call
}

// DeleteApprovalPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - approvalPolicyName string
func (_e *MockService_Expecter) DeleteApprovalPolicy(ctx interface{}, namespaceName interface{}, approvalPolicyName interface{}) *MockService_DeleteApprovalPolicy_Call {
	return &MockService_DeleteApprovalPolicy_Call{Call: _e.mock.On("DeleteApprovalPolicy", ctx, namespaceName, approvalPolicyName)}
}

func (_c *MockService_DeleteApprovalPolicy_Call) Run(run func(ctx context.Context, namespaceName string, approvalPolicyName string)) *MockService_DeleteApprovalPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteApprovalPolicy_Call) Return(_a0 error) *MockService_DeleteApprovalPolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteApprovalPolicy_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteApprovalPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetApprovalPolicy provides a mock function with given fields: ctx, namespaceName, approvalPolicyName
func (_m *MockService) GetApprovalPolicy(ctx context.Context, namespaceName string, approvalPolicyName string) (*v1alpha1.ApprovalPolicy, error) {
	ret := _m.Called(ctx, namespaceName, approvalPolicyName)

	if len(ret) == 0 {
		panic("no return value specified for GetApprovalPolicy")
	}

	var r0 *v1alpha1.ApprovalPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ApprovalPolicy, error)); ok {
		return rf(ctx, namespaceName, approvalPolicyName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ApprovalPolicy); ok {
		r0 = rf(ctx, namespaceName, approvalPolicyName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ApprovalPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, approvalPolicyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetApprovalPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApprovalPolicy'
type MockService_GetApprovalPolicy_Call struct {
	*mock.Call
}

// GetApprovalPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - approvalPolicyName string
func (_e *MockService_Expecter) GetApprovalPolicy(ctx interface{}, namespaceName interface{}, approvalPolicyName interface{}) *MockService_GetApprovalPolicy_Call {
	return &MockService_GetApprovalPolicy_Call{Call: _e.mock.On("GetApprovalPolicy", ctx, namespaceName, approvalPolicyName)}
}

func (_c *MockService_GetApprovalPolicy_Call) Run(run func(ctx context.Context, namespaceName string, approvalPolicyName string)) *MockService_GetApprovalPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetApprovalPolicy_Call) Return(_a0 *v1alpha1.ApprovalPolicy, _a1 error) *MockService_GetApprovalPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetApprovalPolicy_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ApprovalPolicy, error)) *MockService_GetApprovalPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ListApprovalPolicies provides a mock function with given fields: ctx, namespaceName, opts
func (_m *MockService) ListApprovalPolicies(ctx context.Context, namespaceName string, opts services.ListOptions) (*services.ListResult[v1alpha1.ApprovalPolicy], error) {
	ret := _m.Called(ctx, namespaceName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListApprovalPolicies")
	}

	var r0 *services.ListResult[v1alpha1.ApprovalPolicy]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.ApprovalPolicy], error)); ok {
		return rf(ctx, namespaceName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) *services.ListResult[v1alpha1.ApprovalPolicy]); ok {
		r0 = rf(ctx, namespaceName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ApprovalPolicy])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListApprovalPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApprovalPolicies'
type MockService_ListApprovalPolicies_Call struct {
	*mock.Call
}

// ListApprovalPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListApprovalPolicies(ctx interface{}, namespaceName interface{}, opts interface{}) *MockService_ListApprovalPolicies_Call {
	return &MockService_ListApprovalPolicies_Call{Call: _e.mock.On("ListApprovalPolicies", ctx, namespaceName, opts)}
}

func (_c *MockService_ListApprovalPolicies_Call) Run(run func(ctx context.Context, namespaceName string, opts services.ListOptions)) *MockService_ListApprovalPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListApprovalPolicies_Call) Return(_a0 *services.ListResult[v1alpha1.ApprovalPolicy], _a1 error) *MockService_ListApprovalPolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListApprovalPolicies_Call) RunAndReturn(run func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.ApprovalPolicy], error)) *MockService_ListApprovalPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApprovalPolicy provides a mock function with given fields: ctx, namespaceName, ap
func (_m *MockService) UpdateApprovalPolicy(ctx context.Context, namespaceName string, ap *v1alpha1.ApprovalPolicy) (*v1alpha1.ApprovalPolicy, error) {
	ret := _m.Called(ctx, namespaceName, ap)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApprovalPolicy")
	}

	var r0 *v1alpha1.ApprovalPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ApprovalPolicy) (*v1alpha1.ApprovalPolicy, error)); ok {
		return rf(ctx, namespaceName, ap)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ApprovalPolicy) *v1alpha1.ApprovalPolicy); ok {
		r0 = rf(ctx, namespaceName, ap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ApprovalPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ApprovalPolicy) error); ok {
		r1 = rf(ctx, namespaceName, ap)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateApprovalPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApprovalPolicy'
type MockService_UpdateApprovalPolicy_Call struct {
	*mock.Call
}

// UpdateApprovalPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - ap *v1alpha1.ApprovalPolicy
func (_e *MockService_Expecter) UpdateApprovalPolicy(ctx interface{}, namespaceName interface{}, ap interface{}) *MockService_UpdateApprovalPolicy_Call {
	return &MockService_UpdateApprovalPolicy_Call{Call: _e.mock.On("UpdateApprovalPolicy", ctx, namespaceName, ap)}
}

func (_c *MockService_UpdateApprovalPolicy_Call) Run(run func(ctx context.Context, namespaceName string, ap *v1alpha1.ApprovalPolicy)) *MockService_UpdateApprovalPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ApprovalPolicy))
	})
	return _c
}

func (_c *MockService_UpdateApprovalPolicy_Call) Return(_a0 *v1alpha1.ApprovalPolicy, _a1 error) *MockService_UpdateApprovalPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateApprovalPolicy_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ApprovalPolicy) (*v1alpha1.ApprovalPolicy, error)) *MockService_UpdateApprovalPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
